import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'animate.css'
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppin',
  weight: ['100', '200', '400', '900'],
});

export const metadata: Metadata = {
  title: 'Hyperhire',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
